name: attention-all-microbes
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - cython
  - biom-format
  - scikit-bio
  - scikit-learn
  - scipy
  - unifrac
  - click
  - seaborn
  - pip
  - pytest
  - ruff
  - pip:
    - setuptools>=42
    - wheel
    - setuptools_scm
