import click


def aam_model_options(func):
    model_options = [
        click.option('--batch-size',
                     default=8,
                     show_default=True,
                     type=int),
        click.option('--train-percent',
                     default=0.8,
                     show_default=True,
                     type=float),
        click.option('--epochs',
                     default=100,
                     show_default=True,
                     type=int),
        click.option('--repeat',
                     default=1,
                     show_default=True,
                     type=int),
        click.option('--dropout',
                     default=0.8,
                     show_default=True,
                     type=float),
        click.option('--pca-hidden-dim',
                     default=256,
                     show_default=True,
                     type=int),
        click.option('--pca-heads',
                     default=64,
                     show_default=True,
                     type=int),
        click.option('--pca-layers',
                     default=6,
                     show_default=True,
                     type=int),
        click.option('--dff',
                     default=2048,
                     show_default=True,
                     type=int),
        click.option('--d-model',
                     default=128,
                     show_default=True,
                     type=int),
        click.option('--enc_layers',
                     default=6,
                     show_default=True,
                     type=int),
        click.option('--enc-heads',
                     default=8,
                     show_default=True,
                     type=int),
        click.option('--output-dim',
                     default=1,
                     show_default=True,
                     type=int),
        click.option('--lr',
                     default=0.0005,
                     show_default=True,
                     type=float),
        click.option('--max-bp',
                     default=100,
                     show_default=True,
                     type=int),
    ]

    for option in reversed(model_options):
        func = option(func)
    return func
