name: Lint Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run Linters
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install flake8
          pip install ruff

      - name: Run Flake8
        run: flake8 --max-line-length=128

      - name: Run Ruff
        run: ruff . --line-length 128
